### ISSUE TITLE
[Bug]: Unable to ddd item with “type”: “array” json schema

### ISSUE THREAD

**Issue by Reneechen108** [janechu/design-to-code#121]
### What happened?

```
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "firstName": {
        "type": "string"
      },
      "lastName": {
        "type": "string"
      }
    },
    "required": [
      "firstName",
      "lastName"
    ]
  }
}
```
In the json schema defined above, clicking on "add item" results in a ```Type error: undefined is not an object (evaluating 'r.push')``` error

### What package(s) are causing the problem?

design-to-code

### What browsers are you seeing the problem on?

Chrome

**Comment by janechu** [comment]
Unable to reproduce, this appears to be working correctly.
